spring.application.name=lavandus
spring.datasource.url=jdbc:postgresql://localhost:5432/lavandus_db
spring.datasource.username=lavandus_user
spring.datasource.password=lavandus123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Ejecuta data.sql (seed) también contra Postgres y DESPUÉS de que Hibernate cree/actualice las tablas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
