spring.application.name=lavandus
spring.datasource.url=jdbc:postgresql://localhost:5432/lavandus_db
spring.datasource.username=lavandus_user
spring.datasource.password=lavandus123
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
